name: MicaForEveryone

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      ZIP_FILE: MicaForEveryone-${{ matrix.platform }}-${{ matrix.configuration }}.zip
      MSIX_FILE: MicaForEveryone-${{ matrix.platform }}-${{ matrix.configuration }}.msixbundle
      RELEASE_DIR: ${{ github.workflow }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild MicaForEveryone.sln /p:Configuration=$env:Configuration /p:Platform=$env:Platform /t:Restore
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
    
    - name: Build the application
      run: msbuild MicaForEveryone\MicaForEveryone.csproj /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:ReleaseDirectory=$env:RELEASE_DIR /p:ZipName=$env:ZIP_FILE /t:ReleaseZip
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.RELEASE_DIR }}\${{ env.ZIP_FILE }}

    - name: Package as MSIX
      run: msbuild MicaForEveryone.Package\MicaForEveryone.Package.wapproj /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:AppxBundle=Always /p:AppxBundlePlatforms=$env:Platform /p:AppxSigningEnabled=false /p:ErrorOnDuplicatePublishOutputFiles=false /p:ReleaseDirectory=$env:RELEASE_DIR /p:MsixFile=$env:MSIX_FILE /t:ReleaseMsix
      env:
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}

    - name: Upload MSIX
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.RELEASE_DIR }}\${{ env.MSIX_FILE }}
