name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: MicaForEveryone.MicaForEveryone
          installers-regex: 'MicaForEveryone-x64-Release-Installer.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
